FROM node:20.17.0

RUN npm i -g pnpm@9.12.2

WORKDIR /app

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./apps/backend/package.json ./apps/backend/
COPY ./packages/types/package.json ./packages/types/
COPY ./tsconfig.base.json ./turbo.json ./
COPY ./pnpm-lock.yaml ./

RUN pnpm install --no-frozen-lockfile

COPY ./apps/backend/ ./apps/backend/

CMD ["pnpm", "exec", "turbo", "dev", "--filter={./apps/backend}..."]
