FROM node:20.17.0

RUN npm i -g pnpm@9.12.2

WORKDIR /app

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./packages/socket/package.json ./packages/socket/
COPY ./packages/database/package.json ./packages/database/
COPY ./packages/redis/package.json ./packages/redis/
COPY ./packages/types/package.json ./packages/types/
COPY ./packages/rabbitmq/package.json ./packages/rabbitmq/
COPY ./tsconfig.base.json ./turbo.json ./
COPY ./pnpm-lock.yaml ./

RUN pnpm install --no-frozen-lockfile

COPY ./packages/socket/ ./packages/socket/

CMD ["pnpm", "exec", "turbo", "start:docker", "--filter=@mingling/socket"]