FROM node:20.17.0

RUN npm i -g pnpm@9.12.2

WORKDIR /app

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./packages/types/package.json ./packages/types/
COPY ./tsconfig.base.json ./turbo.json ./

RUN pnpm i

COPY ./packages/types/ ./packages/types/

CMD ["pnpm", "exec", "turbo", "start:docker", "--filter={./packages/types}..."]