FROM node:20.17.0

RUN npm i -g pnpm@9.12.2

WORKDIR /app

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./packages/redis/package.json ./packages/redis/
COPY ./packages/types/package.json ./packages/types/
COPY ./tsconfig.base.json ./turbo.json ./
COPY ./pnpm-lock.yaml ./

RUN pnpm install --no-frozen-lockfile

COPY ./packages/redis/ ./packages/redis/

CMD ["pnpm", "exec", "turbo", "start:docker", "--filter=@mingling/redis"]