FROM node:20.17.0

RUN npm i -g pnpm@9.12.2

WORKDIR /app

COPY ./package.json ./pnpm-workspace.yaml ./.npmrc ./
COPY ./packages/database/package.json ./packages/database/
COPY ./packages/types/package.json ./packages/types/
COPY ./tsconfig.base.json ./turbo.json ./
COPY ./pnpm-lock.yaml ./

RUN pnpm install --no-frozen-lockfile

COPY ./packages/database/ ./packages/database/

CMD ["pnpm", "exec", "turbo", "start:docker", "--filter=@mingling/database"]